### ISSUE TITLE
Use Gin POT as an alternative to edit Juniper values

### ISSUE THREAD

**Issue by cdromain** [mnemonicdevices/md001#38]
## Feature request & motivation
Would love to be able to use Gin knob as an alternative/complementary controller to modify values when editing on Juniper, for a different, smoother, more performance oriented gesture when changing values.

## Implementation
This could be simply enabled using a setting in the Global menu.

**Comment by ost-ing** [comment]
Hi @cdromain on initial thought I think this will create a UX clash, e.g. if you assign a modulation source to the POT and then you are modifying values with the POT, there could be some overlap that needs additional cognitive load to deal with. I want to try to keep things as straight forward as possible, and due to the freely assignable nature of inputs I fear that it could be overwhelming and/or confusing for some people

**Comment by cdromain** [comment]
Hey Oliver, I totally get this potential UX conflict issue and am totally with you on keeping things straight forward.
Need to work more with the POT as it stands and think more about it.

**Comment by ost-ing** [comment]
I'll leave this for now then and maybe we can revisit it in the future

**Comment by cdromain** [comment]
Yes I'll think about it more and see if I can figure something out that would keep the best of both worlds !
